# Generated by Django 5.0.6 on 2024-05-08 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ADD_PRODUCT', 'ADD_PRODUCT'), ('ADD_SUPPLIER', 'ADD_SUPPLIER'), ('ADD_TRANSACTION', 'ADD_TRANSACTION'), ('UPDATE_TRANSACTION', 'UPDATE_TRANSACTION')], max_length=20)),
                ('ref_id', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('record_tye', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
