# Generated by Django 5.0.6 on 2024-05-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_record_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_tye',
            new_name='record_type',
        ),
    ]
