# Generated by Django 5.0.6 on 2024-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_record_tye_record_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='action',
            field=models.CharField(choices=[('ADD_PRODUCT', 'ADD_PRODUCT'), ('ADD_SUPPLIER', 'ADD_SUPPLIER'), ('CREATE_SALE_TRANSACTION', 'CREATE_SALE_TRANSACTION'), ('UPDATE_SALE_TRANSACTION', 'UPDATE_SALE_TRANSACTION')], max_length=23),
        ),
    ]
