# Generated by Django 5.0.4 on 2024-04-24 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateField(auto_created=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Clothes', 'Clothes'), ('Cosmetics', 'Cosmetic'), ('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Gaming accessories', 'Gaming accessories')], max_length=18)),
            ],
        ),
    ]
