# Generated by Django 5.0.4 on 2024-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('item', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('address', models.TextField()),
                ('task_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
