# Generated by Django 5.0.4 on 2024-04-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='task_number',
            new_name='tax_number',
        ),
    ]
