# Generated by Django 5.0.4 on 2024-04-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_sale_status_sale_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='ordered_by',
        ),
    ]
