# Generated by Django 5.0.4 on 2024-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_create_at_sale_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'completed'), ('declined', 'declined')], max_length=14),
        ),
    ]
