# Generated by Django 5.0.6 on 2024-05-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_sale_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
